### ISSUE TITLE
LGTM check is applied to all PRs opened before the check was set up

### ISSUE THREAD

**Issue by orangejulius** [lgtmco/lgtm#21]
Hi!
First of all, thanks for LGTM, it's awesome!

One minor issue I noticed just after installing LGTM on a repository that has been active for some time: if you view the [closed pull request page](https://github.com/pelias/wof-admin-lookup/pulls?q=is%3Apr+is%3Aclosed) all previous PRs that were shown as passing with a comforting green checkmark are now shown with the incomplete yellow circle, which is a bit tantalizing.

I'm not sure if this can be fixed, since it might be on Github's side, and it's relatively minor, but it sure would be nice. Here's a screenshot:

![yellowprs](https://cloud.githubusercontent.com/assets/111716/15722936/206e3ee2-280e-11e6-9669-76ad66fa61d8.png)

**Comment by bradrydzewski** [comment]
I think the question is -- what is the desired behavior? Should the approval status be marked as passing if the pull request is closed? or failed? or removed all together? What if the PR is re-opened?

I use cla assist (https://cla-assistant.io/) for my projects and if I close a pull request where the CLA has not been signed we see a similar behavior, where the closed pull request has pending status checks and a yellow circle next to it.

I'm a bit inclined to therefore suggest this needs to be solved at the GitHub level since it impacts multiple services (lgtm, cla-assist, etc) but I'm certainly open to suggestions.

**Comment by orangejulius** [comment]
Yeah that's a good point. For LGTM it seems like the status for PR as a whole should be the same before and after the LGTM approver is added. But for CLA, maybe it makes sense for all the previous PRs to fail so that the CLA can at least be signed after the fact. More signs that point to this being something only Github can help with.

**Comment by bradrydzewski** [comment]
I agree this probably needs to be handled at the GitHub layer, and will close this issue accordingly. The good news is GitHub is still improving this feature every few weeks (as I see the protected branch behavior constantly changing) so hopefully it is something they can address. I'll pass along the feedback.
