### ISSUE TITLE
Overrides existing protected branch settings

### ISSUE THREAD

**Issue by kphelps** [lgtmco/lgtm#29]
Before enabling LGTM, I had "Include Administrators" enabled and other status checks enabled on my protected branch. After enabling LGTM on the repo, "Include Administrators" was disabled and my other status check was disabled, leaving only `approvals/lgtm` enabled.

**Comment by bradrydzewski** [comment]
tracking under #10

**Comment by bradrydzewski** [comment]
because the github protected branches API is unstable and in developer preview, the API behavior has changed significantly since last November. Previously the PATCH didn't replace or overwrite existing information. The API endpoint has now been completely replaced as of last week [1] and LGTM will need to be adjusted accordingly

[1] https://developer.github.com/changes/2016-06-27-protected-branches-api-update/
